add scope methods and validate models
ZayatsAliaksei/test_guru pull request #6
Opened 2021-08-27 22:35 UTC by ZayatsAliaksei

add scope methods and validate models

2021-08-28 21:09 UTC, BubuntuClu requested changes

2021-08-28 21:09 UTC, BubuntuClu commented on app/models/question.rb
> +  # validates :answers, length: { minimum: 1, maximum: 4 } -- такой вариант может быть использован??
нет, он не будет работать так как ты хочешь

2021-08-28 21:09 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add(:answers, "there should be from 1 to 4 answers") if answers.size > 4 || answers.size < 1
1 - минимальную границу не надо задавать, иначе ты не сможешь добавить ответ
2 - эта валидации вопросов. разве при сохранении ответов она будет вызываться?

2021-08-28 21:09 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :sort_tests_by_category, -> (category) { joins(:category).where(categories: { title: category })}
а где потерялись сортировка и выборка?

надо оставить прошлый метод и в нем заченить часть кода на скоуп, а к результату скоупа применить сортировку и выборку, так как их нельзя помещать в скоуп

2021-08-28 21:09 UTC, BubuntuClu commented on app/models/test.rb
> +  validate :title, presence: true, uniqueness: true
уникальность должна быть в паре значения title+level

2021-08-28 21:09 UTC, BubuntuClu commented on app/models/test.rb
> +  validate :title, presence: true, uniqueness: true
так же в БД надо добавить уникальный составной индекс

2021-08-29 18:03 UTC, BubuntuClu commented on app/models/test.rb
> +                                                   .order(title: :desc) }
https://github.com/ZayatsAliaksei/test_guru/pull/6#discussion_r697918372 - уже был комменатрий по поводу этого метода

2021-08-29 19:01 UTC, ZayatsAliaksei commented
исправил

2021-08-29 19:01 UTC, merged