add: views,redirects,helpers,footer and header
ZayatsAliaksei/test_guru pull request #8
Opened 2021-09-07 20:03 UTC by ZayatsAliaksei

невнимательно прочитал и начал работать над вопросами... поэтому посоздавал там вьюхи и контроллер

2021-09-08 17:35 UTC, BubuntuClu requested changes

2021-09-08 17:35 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  "https://github.com/#{author}/#{repo}"
возвращай тут сразу хэлпер `link_to`, сейчас не особо понятней смысл этого метода. он просто подставляет строки в другую строку

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/answer/_form.erb
> +<%= form_with model: @answer,local: true do |form| %>
тут в модели еще вопрос нужен

>Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/answer/index.html.erb
> +  <% if @question%>
а может не быть вопроса? если не будет вопроса у тебя отработает код и будет ошибка что не найден объект, а во вьюхе это можно уже не проверять

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/answer/new.html.erb
> +<!doctype html>
оформляй код правильно во вьюхах. сейчас просто текст, который не понятно читать, так как вложенность не понятна и надо самому "в голове все двигать"

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/answer/show.html.erb
> +<!doctype html>
отступы для оформления верстки

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/questions/index.erb
> +  <% if @test%>
аналогичная ситуация как и во вьюхе тестов.
так же `Список вопросов теста должен выводиться на той же странице, что и сам тест`. то есть этот метод и вьюха не нужны вовсе

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +  <% if @tests%>
тут не нужна проверка. если будет пустой обьъект то код `<% @tests.each do |test| %>` просто ничего не вернет, так как не будет выполняться

2021-09-08 17:35 UTC, BubuntuClu commented on app/views/tests/show.erb
> +<% if @test%>
тут сработает исключение если тест не найдет и вьюха не будет рисоваться

2021-09-08 17:35 UTC, BubuntuClu commented on config/routes.rb
> +  resources :questions do
у тебя происходит дублирование ресурса вопросов. надо на 6ой строке вложить в ресурс вопросов ресурс ответов

2021-09-09 15:45 UTC, ZayatsAliaksei commented on app/views/answer/new.html.erb
> +<!doctype html>
не понял комменатрий, в большинстве своем формирую html  с помощью 
"! + tab"  в  IDE

2021-09-09 16:02 UTC, ZayatsAliaksei commented
не совсем понял что по разметке html сделать нужно поэтом просто удалил все теги ненужные

2021-09-09 17:17 UTC, BubuntuClu commented on app/views/answer/new.html.erb
> +<!doctype html>
видать не везде применяется

2021-09-09 17:18 UTC, BubuntuClu commented on app/views/answer/new.html.erb
> +<!doctype html>
![image](https://user-images.githubusercontent.com/13871063/132732475-51759fc6-b08d-4bee-81d9-2cf883eb11cb.png)
видишь, тут отступов нет у вложенных тегов

2021-09-09 17:39 UTC, merged